In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Problem Statement:

# Artificial Neural Network

## Importing the Library

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf

In [ ]:
print('Tensorflow version',tf.__version__)
print('Pandas Version',pd.__version__)
print('Numpy Version',np.__version__)
print('Seaborn version',sns.__version__)

Tensorflow version 2.8.2
Pandas Version 1.3.5
Numpy Version 1.21.6
Seaborn version 0.11.2

## Part 1: Data Preprocessing

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [ ]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
RowNumber,10000.0,5.000500e+03,2886.895680,1.00,2500.75,5.000500e+03,7.500250e+03,10000.00
CustomerId,10000.0,1.569094e+07,71936.186123,15565701.00,15628528.25,1.569074e+07,1.575323e+07,15815690.00
CreditScore,10000.0,6.505288e+02,96.653299,350.00,584.00,6.520000e+02,7.180000e+02,850.00
Age,10000.0,3.892180e+01,10.487806,18.00,32.00,3.700000e+01,4.400000e+01,92.00
Tenure,10000.0,5.012800e+00,2.892174,0.00,3.00,5.000000e+00,7.000000e+00,10.00
Balance,10000.0,7.648589e+04,62397.405202,0.00,0.00,9.719854e+04,1.276442e+05,250898.09
NumOfProducts,10000.0,1.530200e+00,0.581654,1.00,1.00,1.000000e+00,2.000000e+00,4.00
HasCrCard,10000.0,7.055000e-01,0.455840,0.00,0.00,1.000000e+00,1.000000e+00,1.00
IsActiveMember,10000.0,5.151000e-01,0.499797,0.00,0.00,1.000000e+00,1.000000e+00,1.00
EstimatedSalary,10000.0,1.000902e+05,57510.492818,11.58,51002.11,1.001939e+05,1.493882e+05,199992.48
Exited,10000.0,2.037000e-01,0.402769,0.00,0.00,0.000000e+00,0.000000e+00,1.00

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
# Check missing value in the data set

dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
# If Present
#from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values=np.nan, startegy='mean')
# imputer.fit(dataset)
# dataset = imputer.transform(dataset)

In [ ]:
# Drop the unused column
# Process 1
# dataset.drop(['RowNumber','CustomerId','Surname'], axis = 1, inplace = True)
# Process 2
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

In [ ]:
print(y)

[1 0 1 ... 1 1 0]

## Encoding Categorical Data

### Label Encoding the "gender' column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]

### OneHot Encoding Geography column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]

## Splitting the dataset into the training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .20, random_state = 0)

In [ ]:
print('X_train shape',X_train.shape)
print('X_test shape', X_test.shape)
print('y_train shpae', y_train.shape)
print('y_test shape', y_test.shape)

X_train shape (8000, 12)
X_test shape (2000, 12)
y_train shpae (8000,)
y_test shape (2000,)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Intializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation= 'relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 , activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid' ))

## Training the output layer

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss= 'binary_crossentropy' , metrics= ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size= 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4929 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4701 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4532 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4430 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4362 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4309 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4217 - accuracy: 0.8070
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4175 - accuracy: 0.8214
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8235
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4102 - accuracy: 0.8275
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8300
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4010 - accuracy: 0.8319
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3955 - accuracy: 0.8335
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3895 - accuracy: 0.8367
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.8406
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3787 - accuracy: 0.8446
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3741 - accuracy: 0.8466
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3702 - accuracy: 0.8491
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3672 - accuracy: 0.8515
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3645 - accuracy: 0.8547
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8539
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3613 - accuracy: 0.8554
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3598 - accuracy: 0.8551
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3587 - accuracy: 0.8559
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8576
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8584
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.8572
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8587
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3522 - accuracy: 0.8570
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3513 - accuracy: 0.8575
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3502 - accuracy: 0.8590
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3494 - accuracy: 0.8599
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3485 - accuracy: 0.8591
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3480 - accuracy: 0.8610
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3468 - accuracy: 0.8602
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3457 - accuracy: 0.8614
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3450 - accuracy: 0.8622
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8597
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3439 - accuracy: 0.8619
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8614
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3424 - accuracy: 0.8615
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3427 - accuracy: 0.8606
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3420 - accuracy: 0.8631
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3418 - accuracy: 0.8615
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3417 - accuracy: 0.8614
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8621
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8637
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8626
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3403 - accuracy: 0.8616
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3401 - accuracy: 0.8633
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3395 - accuracy: 0.8629
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3391 - accuracy: 0.8635
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3392 - accuracy: 0.8636
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3383 - accuracy: 0.8648
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 0.8630
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3382 - accuracy: 0.8645
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8624
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8635
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8639
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8630
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8652
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8635
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8633
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8637
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3368 - accuracy: 0.8636
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8639
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8622
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8651
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8626
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8626
Epoch 73/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8631
Epoch 74/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3362 - accuracy: 0.8643
Epoch 75/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8640
Epoch 76/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8645
Epoch 77/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3358 - accuracy: 0.8622
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3359 - accuracy: 0.8646
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8627
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8649
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8649
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3355 - accuracy: 0.8629
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8640
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8649
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3350 - accuracy: 0.8635
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8634
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3359 - accuracy: 0.8630
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3359 - accuracy: 0.8643
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3353 - accuracy: 0.8645
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3352 - accuracy: 0.8630
Epoch 91/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8646
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3350 - accuracy: 0.8631
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3350 - accuracy: 0.8637
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3354 - accuracy: 0.8633
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8622
Epoch 96/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8634
Epoch 97/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8637
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3350 - accuracy: 0.8652
Epoch 99/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8631
Epoch 100/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8615

## Part 4: making the prediction and evaluating the model

### Homework
Use our ANN model to predict if the customer with the following informations will leave the bank:


1.   Geography: France
2. Credit Score:600
3. Gender: Male
4. Age: 40 years old
5. Tenure: 3 years 
6. Balance: 60000
7. Number of Products: 2
8. Does this customer have a credit card? Yes
9. Is this customer an Active Member : Yes
10. Estimated Salary: $50000

So, should we say goodbye to that customer

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600,1,40,3,6000,2,1,1,50000]])))

[[0.01596695]]

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]])) > 0.5)

[[False]]

Therefore, Our ANN model predicts that this customer stays in the bank

Import Note1: Notice that the values of the features were all input in a double pair of square brackets. That's beacuse the 'predict' method always expect the 2D array as the format of its inputs & putting our values into a double pair of square brackets makes the input exactly a 2D array

Important Note 2:
Notices also that the "France" country was not impute as a string in the last column but as "1,0,0" in the first three column. That's because of course the predict method expect the One-Hot encoded values of the state, & as we see in the first row of the matix of features X,"France" was encoded as "1,0,0". and be careful to include these values in the first three columns, because the dummy varaibles are always created in the first column.

## Predict the test result

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > .5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

## Making the Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 196  209]]

0.8615